### ISSUE TITLE
Create Min and Max Debit Credit

### ISSUE THREAD

**Issue by yusriltakeuchi** [himanshusingh335/check_my_cash#9]
**Is your feature request related to a problem? Please describe.**
In the overview section it only shows the total credit and debit, I think there is still something missing

**Describe the solution you'd like**
Can i create Pull Request to find Min and Max Credit and Debit in 'Total Field' ? This can make it easier for users to find out what the largest credit or smallest debit is

![Screenshot_1633151792](https://user-images.githubusercontent.com/10339660/135704805-1b484c11-ef2e-4d3e-b9e2-36ba591bd955.png)

**Comment by himanshusingh335** [comment]
The Min, Max Credit and Debit feature in 'Total Field' in total field would be a good addition.

However be advised, I had written this flutter code in my learning days, because of this, there is not componentization of code on the UI side. So it might be a bit difficult for you to make sense of the code 😅

**Comment by yusriltakeuchi** [comment]
> The Min, Max Credit and Debit feature in 'Total Field' in total field would be a good addition.
> 
> However be advised, I had written this flutter code in my learning days, because of this, there is not componentization of code on the UI side. So it might be a bit difficult for you to make sense of the code 😅

It’s okay, i’ll following this coding style. I will try send the screenshot result in here after done

**Comment by yusriltakeuchi** [comment]
Hi @himanshusingh335, I've made changes to this issue, here are the results. There is a summary for the min and max of debits and credits.

![Screenshot_1633178872](https://user-images.githubusercontent.com/10339660/135716861-31170497-d030-4fa9-92ac-78a80b984701.png)


If you're okay with this change, I'll make a PR and explain what I changed there.

**Comment by himanshusingh335** [comment]
The changes are good, data is relevant to the app. If no discrepancies are found during review, I will merge the changes.

The min and max debit/credit shown is for the entire transaction history, correct ?

**Comment by yusriltakeuchi** [comment]
> The changes are good, data is relevant to the app. If no discrepancies are found during review, I will merge the changes.
> 
> The min and max debit/credit shown is for the entire transaction history, correct ?

Yes, i find the value from the history
